// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCypyg6V1CyS_vg3Cn31E1wwnz0qxpBnUI',
    appId: '1:621905064804:web:faf571dd4aec4ca3b90071',
    messagingSenderId: '621905064804',
    projectId: 'ulab-blood-bank-c3665',
    authDomain: 'ulab-blood-bank-c3665.firebaseapp.com',
    databaseURL: 'https://ulab-blood-bank-c3665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ulab-blood-bank-c3665.appspot.com',
    measurementId: 'G-NYNXKCWR66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVGRgszlnDV1kf7Xc0-i4Cv3mVChByyQ',
    appId: '1:621905064804:android:df02d5f8a030a25ab90071',
    messagingSenderId: '621905064804',
    projectId: 'ulab-blood-bank-c3665',
    databaseURL: 'https://ulab-blood-bank-c3665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ulab-blood-bank-c3665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtD6gyWCcaD6i4mY7oaFxx8eSZPtMmpw',
    appId: '1:621905064804:ios:b34a84ef0ab97fe6b90071',
    messagingSenderId: '621905064804',
    projectId: 'ulab-blood-bank-c3665',
    databaseURL: 'https://ulab-blood-bank-c3665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ulab-blood-bank-c3665.appspot.com',
    iosBundleId: 'bd.edu.ulab.ulabBloodBank',
  );
}
